version: 2.1

orbs:
  python: circleci/python@2.0.3
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    machine:
      image: ubuntu-2204:2023.02.1
      docker_layer_caching: true
    resource_class: medium
    parameters:
      tag:
        default: "3.8"
        type: string
    steps:
      - checkout
      - run:
          name: Install python
          command: python3 --version
      - run:
          name: Startup the Speckle Server
          command: docker compose -f docker-compose.yml up -d
      - run:
          command: python3 -m pip install --upgrade pip
          name: upgrade pip
      - run:
          name: Install packages
          command: |
            python3 -m pip install poetry
            poetry install
      - run: poetry run pytest --cov --cov-report xml:reports/coverage.xml --junitxml=reports/test-results.xml
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - codecov/upload

  test-old:
    docker:
      - image: "cimg/python:<<parameters.tag>>"
      - image: "cimg/node:16.15"
      - image: "cimg/redis:6.2"
      - image: "cimg/postgres:14.2"
        environment:
          POSTGRES_DB: speckle2_test
          POSTGRES_PASSWORD: speckle
          POSTGRES_USER: speckle
      - image: "speckle/speckle-server"
        command: ["bash", "-c", "/wait && node bin/www"]
        environment:
          POSTGRES_URL: "127.0.0.1"
          POSTGRES_USER: "speckle"
          POSTGRES_PASSWORD: "speckle"
          POSTGRES_DB: "speckle2_test"
          REDIS_URL: "redis://127.0.0.1"
          SESSION_SECRET: "keyboard cat"
          STRATEGY_LOCAL: "true"
          CANONICAL_URL: "http://localhost:3000"
          WAIT_HOSTS: 127.0.0.1:5432, 127.0.0.1:6379
          DISABLE_FILE_UPLOADS: "true"
    parameters:
      tag:
        default: "3.8"
        type: string
    steps:
      - checkout
      - run: python --version
      - run:
          command: python -m pip install --upgrade pip
          name: upgrade pip
      - python/install-packages:
          pkg-manager: poetry
      - run: poetry run pytest --cov --cov-report xml:reports/coverage.xml --junitxml=reports/test-results.xml

      - store_test_results:
          path: reports

      - store_artifacts:
          path: reports

      - codecov/upload

  deploy:
    docker:
      - image: "cimg/python:3.8"
    steps:
      - checkout
      - run: python patch_version.py $CIRCLE_TAG
      - run: poetry build
      - run: poetry publish -u __token__ -p $PYPI_TOKEN

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              tag: ["3.11"]
          filters:
            tags:
              only: /.*/
      - deploy:
          context: pypi
          requires:
            - test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/ # For testing only! /ci\/.*/
