version: 2.1

orbs:
  python: circleci/python@2.0.3
  codecov: codecov/codecov@3.2.2

jobs:
  test:
    machine:
      image: ubuntu-2204:2023.02.1
      docker_layer_caching: true
    resource_class: medium
    parameters:
      tag:
        default: "3.11"
        type: string
    steps:
      - checkout
      - run:
          name: Install python
          command: |
            pyenv install -s << parameters.tag >>
            pyenv global << parameters.tag >>
      - run:
          name: Startup the Speckle Server
          command: docker compose -f docker-compose.yml up -d
      - run:
          name: Install Poetry
          command: |
            pip install poetry
      - run:
          name: Install packages
          command: poetry install
      - run:
          name: Run tests
          command: poetry run pytest --cov --cov-report xml:reports/coverage.xml --junitxml=reports/test-results.xml
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - codecov/upload

  deploy:
    docker:
      - image: "cimg/python:3.8"
    steps:
      - checkout
      - run: python patch_version.py $CIRCLE_TAG
      - run: poetry build
      - run: poetry publish -u __token__ -p $PYPI_TOKEN

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              tag: ["3.11"]
          filters:
            tags:
              only: /.*/
      - deploy:
          context: pypi
          requires:
            - test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/ # For testing only! /ci\/.*/
