version: "3.3"  # optional since v1.27.0
services:
  postgres:
    image: cimg/postgres:14.2
    environment:
      POSTGRES_DB: speckle2_test
      POSTGRES_PASSWORD: speckle
      POSTGRES_USER: speckle
    network_mode: host
  redis:
    image: cimg/redis:6.2
    network_mode: host
  speckle-server:
    image: speckle/speckle-server:latest
    command: ["bash", "-c", "/wait && node bin/www"]
    environment:
      POSTGRES_URL: "localhost"
      POSTGRES_USER: "speckle"
      POSTGRES_PASSWORD: "speckle"
      POSTGRES_DB: "speckle2_test"
      REDIS_URL: "redis://localhost"
      SESSION_SECRET: "keyboard cat"
      STRATEGY_LOCAL: "true"
      CANONICAL_URL: "http://localhost:3000"
      WAIT_HOSTS: localhost:5432, localhost:6379
      DISABLE_FILE_UPLOADS: "true"
    network_mode: host

  specklepy:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        VARIANT: 3.9
        NODE_VERSION: lts/*
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - ..:/workspaces/specklepy:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: host
# networks:
#     default: